version: '3.8'

services:
  oss:
    image: 'bitnami/minio:2022.4.9'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
    ports:
      - "9020:9000"
      - "19020:9001"
    volumes:
      - oss-data:/data
    networks:
      - laf_shared_network

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd-data:/bitnami/etcd/data
    ports:
      - 12379:2379
      - 12380:2380
    networks:
      - laf_shared_network

volumes:
  oss-data:
  etcd-data:

networks:
  laf_shared_network:
    external: true
